name: 20-sync-all-qa-deployments

# This workflow checks if all required checks have passed before allowing a pull request to be merged.
# It is triggered on pull request events and uses the GitHub CLI to check the status of checks.
# The workflow will wait for all other checks to finish before proceeding.
# If any of the required checks fail, the workflow will exit with an error.


on:
  workflow_dispatch:
  push:
    branches: [ main]
    paths: [.github/workflows/20-sync-all-qa-deployments.yml]
  # schedule:
  #   - cron: '0 16 * * *' 

env:
    PROJECTS: "{ \"01\": \"courses\", \"02\": \"courses\", \"03\": \"courses\", \"04\": \"dining\", \"05\": \"courses\", \"06\": \"dining\", \"07\": \"frontiers\", \"08\": \"dining\", \"09\": \"frontiers\", \"10\": \"dining\", \"11\": \"frontiers\", \"12\": \"frontiers\", \"13\": \"rec\", \"14\": \"rec\", \"15\": \"rec\", \"16\": \"rec\" }"

jobs:
  deploy:
    strategy:
      fail-fast: false    # If one part of the matrix fails, do not stop the others.   
      matrix:
        TEAM: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16"]
    runs-on: ubuntu-latest
    env:
      DOKKU: ${{ matrix.TEAM }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H csil.cs.ucsb.edu >> ~/.ssh/known_hosts
        shell: bash
      - name: Set environment variables
        env:
          PROJECT: ${{ fromJson(env.PROJECTS)[env.DOKKU] }}
        run: |
          echo "REPO=https://github.com/${{ github.repository_owner }}/proj-${PROJECT}-s25-${{ env.DOKKU }}" >> $GITHUB_ENV
          echo "PROJECT=${{ fromJson(env.PROJECTS)[env.DOKKU] }}" >> $GITHUB_ENV

      - name: SSH and run commands
        run: |
          ssh -i ~/.ssh/id_ed25519 pconrad@csil.cs.ucsb.edu ${{ env.DOKKU }} config:set --no-restart ${{ env.PROJECT }}-qa SOURCE_REPO=${{ env.REPO }}
          ssh -i ~/.ssh/id_ed25519 pconrad@csil.cs.ucsb.edu ${{ env.DOKKU }} config:set --no-restart ${{ env.PROJECT }}-qa ADMIN_EMAILS=${{ secrets.ADMIN_EMAILS_QA || 'phtcon@ucsb.edu' }}
          ssh -i ~/.ssh/id_ed25519 pconrad@csil.cs.ucsb.edu ${{ env.DOKKU }} git:sync ${{ env.PROJECT }}-qa ${{ env.REPO }} main
          ssh -i ~/.ssh/id_ed25519 pconrad@csil.cs.ucsb.edu ${{ env.DOKKU }} ps:rebuild ${{ env.PROJECT }}-qa 
          
